In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.preprocessing import scale,LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit,train_test_split
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib

In [2]:
def print_metrics(y_true,y_pred):
    print("accurracy: {}".format(accuracy_score(y_true,y_pred)))
    #print("f1: {}".format(f1_score(y_true,y_pred,average="macro")))   

In [3]:
data_folder = '../../preprocessed_data/area_data'
result_folder = '../../serialized/forest'

In [4]:
test_scores = np.array(pd.read_csv('test_recomendations.csv'))
for file in os.listdir(data_folder):
    data = pd.read_csv(os.path.join(data_folder, file))
    X = np.array(data[["mat","len","cie","his","nem"]])
    #y = np.array(data.apply(lambda x: "{}/{}".format(x['universidad'],x['tuni_carreer_name']),axis=1))
    y = np.array(data['tuni_carreer_id'])
#     lb = LabelEncoder()
#     lb.fit(y)
#     y_encoded = lb.transform(y)
    #X_scaled = scale(X)
    #randomized stratified test/train split
    print(file)
    sss = StratifiedShuffleSplit(n_splits=5, train_size=0.8, random_state=0)
    try:
        for train_index,test_index in sss.split(X, y):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            model = RandomForestClassifier(25,min_samples_split=5,n_jobs=-1)
            model.fit(X_train,y_train)
            result = model.predict(X_test)
            print_metrics(y_test,result)
    except ValueError:
        print("{} failed!".format(file))
    model = RandomForestClassifier(25,min_samples_split=5,n_jobs=-1)
    model.fit(X,y)
    clases = model.classes_
    result = model.predict_proba(test_scores)
    for i in range(test_scores.shape[0]):
        print(test_scores[i])
        best = np.argpartition(result[i],-3)[-3:]
        for index in best:
            print("{}, prob: {}".format(clases[index],result[i][index]))
    joblib.dump(model,os.path.join(result_folder,os.path.splitext(file)[0]))
    

9_data.csv
accurracy: 0.1000383288616328
accurracy: 0.09773859716366425
accurracy: 0.09965504024530472
accurracy: 0.1004216174779609
accurracy: 0.10195477194327328
[830 700 778   0 720]
402, prob: 0.1562857142857143
538, prob: 0.22590476190476189
58, prob: 0.4091428571428572
[830 700 778 680 720]
402, prob: 0.10695238095238095
538, prob: 0.26590476190476187
58, prob: 0.4024761904761905
[500 450 580   0 670]
1308, prob: 0.08085714285714285
1144, prob: 0.1
728, prob: 0.10400000000000001
[400 430   0 450 500]
672, prob: 0.098
1308, prob: 0.13606349206349205
846, prob: 0.30433333333333334
[620 730   0 680 620]
965, prob: 0.08444444444444445
262, prob: 0.11266666666666665
452, prob: 0.6015555555555556
2_data.csv
accurracy: 0.3475177304964539
accurracy: 0.28368794326241137
accurracy: 0.3262411347517731
accurracy: 0.2907801418439716
accurracy: 0.3262411347517731
[830 700 778   0 720]
370, prob: 0.14133333333333334
20, prob: 0.29355555555555557
21, prob: 0.4566666666666667
[830 700 778 680 720