In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.preprocessing import scale,LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit,train_test_split
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib

In [2]:
def print_metrics(y_true,y_pred):
    print("accurracy: {}".format(accuracy_score(y_true,y_pred)))
    #print("f1: {}".format(f1_score(y_true,y_pred,average="macro")))   

In [3]:
data_folder = '../../preprocessed_data/area_data'
result_folder = '../../serialized/forest'

In [4]:
test_scores = np.array(pd.read_csv('test_recomendations.csv'))
for file in os.listdir(data_folder):
    data = pd.read_csv(os.path.join(data_folder, file))
    X = np.array(data[["mat","len","cie","his","nem"]])
    #y = np.array(data.apply(lambda x: "{}/{}".format(x['universidad'],x['tuni_carreer_name']),axis=1))
    y = np.array(data['tuni_carreer_id'])
#     lb = LabelEncoder()
#     lb.fit(y)
#     y_encoded = lb.transform(y)
    #X_scaled = scale(X)
    #randomized stratified test/train split
    print(file)
    sss = StratifiedShuffleSplit(n_splits=5, train_size=0.8, random_state=0)
    try:
        for train_index,test_index in sss.split(X, y):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            model = RandomForestClassifier(25,min_samples_split=5,n_jobs=-1)
            model.fit(X_train,y_train)
            result = model.predict(X_test)
            print_metrics(y_test,result)
    except ValueError:
        print("{} failed!".format(file))
    model = RandomForestClassifier(25,min_samples_split=5,n_jobs=-1)
    model.fit(X,y)
    clases = model.classes_
    result = model.predict_proba(test_scores)
    for i in range(test_scores.shape[0]):
        print(test_scores[i])
        best = np.argpartition(result[i],-3)[-3:]
        for index in best:
            print("{}, prob: {}".format(clases[index],result[i][index]))
    joblib.dump(model,os.path.join(result_folder,os.path.splitext(file)[0]))
    

9_data.csv
accurracy: 0.09754925516578568
accurracy: 0.09658817876021143
accurracy: 0.11484863046612205
accurracy: 0.10139356078808265
accurracy: 0.10523786641037962
[830 700 778   0 720]
402, prob: 0.12266666666666666
538, prob: 0.21266666666666667
58, prob: 0.45266666666666666
[830 700 778 680 720]
442, prob: 0.09333333333333334
538, prob: 0.19266666666666665
58, prob: 0.4866666666666667
[500 450 580   0 670]
1031, prob: 0.10704761904761904
728, prob: 0.12971428571428573
731, prob: 0.1595238095238095
[400 430   0 450 500]
672, prob: 0.08
745, prob: 0.16733333333333333
759, prob: 0.45866666666666667
[620 730   0 680 620]
966, prob: 0.068
262, prob: 0.16666666666666663
452, prob: 0.47
2_data.csv
accurracy: 0.2857142857142857
accurracy: 0.31868131868131866
accurracy: 0.34065934065934067
accurracy: 0.3076923076923077
accurracy: 0.3076923076923077
[830 700 778   0 720]
21, prob: 0.1537777777777778
370, prob: 0.16666666666666669
93, prob: 0.45422222222222225
[830 700 778 680 720]
1304, pro