In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.preprocessing import scale,LabelEncoder
from sklearn.model_selection import StratifiedShuffleSplit,train_test_split
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib

In [2]:
def print_metrics(y_true,y_pred):
    print("accurracy: {}".format(accuracy_score(y_true,y_pred)))
    #print("f1: {}".format(f1_score(y_true,y_pred,average="macro")))   

In [3]:
data_folder = '../../preprocessed_data/area_data'
result_folder = '../../serialized/forest'

In [5]:
test_scores = np.array(pd.read_csv('test_recomendations.csv'))
for file in os.listdir(data_folder):
    data = pd.read_csv(os.path.join(data_folder, file))
    X = np.array(data[["mat","len","cie","his","nem"]])
    y = np.array(data.apply(lambda x: "{}/{}".format(x['universidad'],x['tuni_carreer_name']),axis=1))
#     lb = LabelEncoder()
#     lb.fit(y)
#     y_encoded = lb.transform(y)
    #X_scaled = scale(X)
    #randomized stratified test/train split
    print(file)
    sss = StratifiedShuffleSplit(n_splits=5, train_size=0.8, random_state=0)
    try:
        for train_index,test_index in sss.split(X, y):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]
            model = RandomForestClassifier(25,min_samples_split=5,n_jobs=-1)
            model.fit(X_train,y_train)
            result = model.predict(X_test)
            print_metrics(y_test,result)
    except ValueError:
        print("{} failed!".format(file))
    model = RandomForestClassifier(25,min_samples_split=5,n_jobs=-1)
    model.fit(X,y)
    clases = model.classes_
    result = model.predict_proba(test_scores)
    for i in range(test_scores.shape[0]):
        print(test_scores[i])
        best = np.argpartition(result[i],-3)[-3:]
        for index in best:
            print("{}, prob: {}".format(clases[index],result[i][index]))
    joblib.dump(model,os.path.join(result_folder,os.path.splitext(file)[0]))
    

9_data.csv
accurracy: 0.10080490609428899
accurracy: 0.09505557684936758
accurracy: 0.10195477194327328
accurracy: 0.09505557684936758
accurracy: 0.09620544269835186
[830 700 778   0 720]
UACH/medicina , prob: 0.15103174603174602
UFRO/medicina, prob: 0.2361111111111111
UCH/medicina , prob: 0.38833333333333336
[830 700 778 680 720]
UACH/medicina , prob: 0.14633333333333332
UFRO/medicina, prob: 0.15388888888888888
UCH/medicina , prob: 0.3428888888888889
[500 450 580   0 670]
UPA/nutrición dietética, prob: 0.08933333333333333
UNAB/medicina veterinaria, prob: 0.11066666666666666
UNAB/nutrición dietética, prob: 0.12399999999999999
[400 430   0 450 500]
UMAYO/medicina veterinaria, prob: 0.13333333333333333
UNAB/psicología, prob: 0.15333333333333332
UTA/psicología, prob: 0.2477777777777778
[620 730   0 680 620]
UDEC/psicología, prob: 0.09300000000000001
USACH/psicología, prob: 0.126
UDP/psicología, prob: 0.5579523809523809
2_data.csv
accurracy: 0.2978723404255319
accurracy: 0.3262411347517731

accurracy: 0.2861736334405145
accurracy: 0.2765273311897106
accurracy: 0.2765273311897106
accurracy: 0.22186495176848875
accurracy: 0.31511254019292606
[830 700 778   0 720]
UCH/quimica  lic química, prob: 0.15514285714285714
UCH/ingeniería biotecnología molecular, prob: 0.20609523809523808
PUC/física, prob: 0.311047619047619
[830 700 778 680 720]
PUC/física, prob: 0.15361904761904763
UCH/ingeniería biotecnología molecular, prob: 0.15876190476190474
UCH/pedadogía ed  media matemática física, prob: 0.28514285714285714
[500 450 580   0 670]
PUCV/bioquímica, prob: 0.12804761904761905
UTA/ingeniería química ambiental, prob: 0.27385714285714285
UNAB/química farmacia, prob: 0.15238095238095237
[400 430   0 450 500]
UDEC/bachillerato humanidades, prob: 0.15742857142857145
UNAB/química farmacia, prob: 0.23866666666666667
UTA/ingeniería química ambiental, prob: 0.37266666666666665
[620 730   0 680 620]
UCH/cine televisión, prob: 0.1791111111111111
UCH/periodismo, prob: 0.2603636363636364
UCH/pr